services:
  database:
    image: mysql:lts
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ANDPMSHXPT1V5kv5pfqmjGMhVzbcpXTe"

